# Generated by Django 3.2 on 2022-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Upload an image', null=True, upload_to='images/products', verbose_name='image'),
        ),
    ]
