# Generated by Django 3.2 on 2022-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/images/blank.jpg', help_text='Upload an image', upload_to='images/products', verbose_name='image'),
        ),
    ]
