# Generated by Django 4.0.5 on 2022-07-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('it', 'IT'), ('food', 'Food'), ('sport', 'Sport'), ('study', 'Study'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('house', 'House'), ('books', 'Books'), ('service', 'Service'), ('weapons', 'Weapons')], max_length=50, unique=True, verbose_name='category name'),
        ),
    ]
