# Generated by Django 4.0.5 on 2022-07-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/images/blank.jpg', help_text='Upload an image', upload_to='images/products', verbose_name='image'),
        ),
    ]
