# Generated by Django 4.0.5 on 2022-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='used_coupones',
            field=models.ManyToManyField(blank=True, null=True, to='products.couponcode'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
