# Generated by Django 4.0.5 on 2022-07-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='../static/images/blank.jpg', help_text='Upload an avatar', upload_to='images/profile_pics', verbose_name='image'),
        ),
    ]
