# Generated by Django 4.0.5 on 2022-07-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_level_remove_category_lft_and_more'),
        ('users', '0002_alter_useraccount_used_coupones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='used_coupones',
            field=models.ManyToManyField(blank=True, to='products.couponcode'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
