# Generated by Django 4.0.5 on 2022-06-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='address',
            new_name='location',
        ),
    ]
