# Generated by Django 4.0.5 on 2022-06-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0002_rename_address_useraccount_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='wishlist',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location(country and/or city)'),
        ),
    ]
