# Generated by Django 4.0.5 on 2022-06-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_wishlist_alter_useraccount_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone'),
        ),
    ]
