# Generated by Django 4.0.5 on 2022-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_couponcode_reduce_amount'),
        ('users', '0004_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='used_coupones',
            field=models.ManyToManyField(to='products.couponcode'),
        ),
    ]
