# Generated by Django 3.2 on 2022-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Upload an avatar', null=True, upload_to='images/profile_pics', verbose_name='image'),
        ),
    ]
