# Generated by Django 3.2 on 2022-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='../static/images/blank.jpg', help_text='Upload an avatar', upload_to='images/profile_pics', verbose_name='image'),
        ),
    ]
