# Generated by Django 3.2 on 2022-08-30 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='report_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_author', to='users.useraccount'),
        ),
    ]
