# Generated by Django 4.0.5 on 2022-07-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shipping'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='description',
            field=models.CharField(default=0, max_length=150, verbose_name='shipping type description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='type',
            field=models.CharField(choices=[('same day delivery', 'Same day delivery'), ('overnight delivery', 'Overnight delivery'), ('slow delivery', 'Slow delivery')], max_length=50, unique=True, verbose_name='shipping type'),
        ),
    ]
