# Generated by Django 4.0.5 on 2022-07-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_amount_order_price_order_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
