# Generated by Django 4.0.5 on 2022-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='type',
            field=models.CharField(choices=[('Same day delivery', 'same day delivery'), ('Overnight delivery', 'overnight delivery'), ('Slow delivery', 'slow delivery')], max_length=50, unique=True, verbose_name='shipping type'),
        ),
    ]
