# Generated by Django 4.0.5 on 2022-07-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_shipping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='type',
            field=models.CharField(choices=[('same day delivery', 'Same day delivery'), ('overnight delivery', 'Overnight delivery'), ('slow delivery', 'Slow delivery')], max_length=50, unique=True, verbose_name='shipping type'),
        ),
    ]
