# Generated by Django 4.0.5 on 2022-07-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('it', 'IT'), ('food', 'Food'), ('sport', 'Sport'), ('study', 'Study'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('house', 'House'), ('books', 'Books')], max_length=50, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.tag'),
        ),
    ]
