# Generated by Django 4.0.5 on 2022-07-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('it', 'IT'), ('food', 'Food'), ('sport', 'Sport'), ('study', 'Study'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('house', 'House'), ('books', 'Books'), ('service', 'Service')], max_length=50, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('viral', 'Viral'), ('school', 'School'), ('new', 'New'), ('old', 'Old'), ('very cheap', 'Very cheap'), ('natural', 'Natural'), ('punk', 'Punk'), ('animals', 'Animals'), ('computer', 'Computers'), ('programming', 'Programming'), ('funny', 'Funny'), ('football', 'Football'), ('anime', 'Anime')], max_length=50, unique=True, verbose_name='tag name'),
        ),
    ]
