# Generated by Django 4.0.5 on 2022-07-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='reduce_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
